version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'NMS_FRONTEND'
    volumes: 
      - '/public:/app/public'
      - '/src:/app/src'
    ports:
      - '8006:8006'
